<h1>Kategorien</h1>

<?php if ($this->param !== true): ?>
	<a href="/question">Zurück</a>
	<?php foreach ($this->categories as $category): ?>
		<a href='/question/category/cat/<?php echo $category['key']; ?>'><?php echo $category['name']. '('. $category['count'] . ')'; ?></a>
		<a href='/game/index/play/<?php echo md5('nextgame!'); ?>/cat/<?php echo $category['key']; ?>/sh/1'>Spielen</a>
		<a href='/game/index/play/<?php echo md5('nextgame!'); ?>/cat/<?php echo $category['key']; ?>/qtyp/mc/sh/1'>MultipleChoice</a>
		<a href='/game/index/play/<?php echo md5('nextgame!'); ?>/cat/<?php echo $category['key']; ?>/qtyp/txt/sh/1'>Direkteingabe</a>
		<br />
	<?php endforeach; ?>
<?php endif; ?>

<?php if (isset($this->paginator)): ?>
	<a href="/question/category">Zurück</a>
	<?php foreach ($this->paginator as $question): ?>
		<img height="100px" src="<?php echo $this->baseUrl . '/img/question/' . $question['question']['image']; ?>" />
		<a href="/question/play/question/<?php echo $question['question']['questionid']; ?>/back/<?php echo $question['backUrl']; ?>">
			<?php echo $question['question']['question']; ?><br />
		</a>
	<?php endforeach; ?>

	<?php echo $this->paginationControl(
					$this->paginator,
					'Sliding',
					'/partials/pagination.phtml'); ?>
<?php endif; ?>
