<h1>Question</h1>

<p>Aktuell gibt es bei uns <?php echo $this->countQuestion; ?> Fragen</p>

<p>Durchsuchen Sie doch unseren Fragekatalog:</p>

<?php if ($this->sortDate === true): ?>
	<a href="/question">Zufallssortierung</a>
<?php else: ?>
	<a href="/question/index/mode/d">Neueste Fragen zuerst</a>
<?php endif; ?>

<a href="/question/category">Zu unseren Kategorien</a>
	
<?php foreach ($this->paginator as $question): ?>
	<img height="100px" src="<?php echo $this->baseUrl . '/img/' . $question['question']['image'] . '.jpg'; ?>" />
	<a href="/question/play/question/<?php echo $question['question']['questionid']; ?>/back/<?php echo $question['backUrl']; ?>">
		<?php echo $question['question']['question']; ?><br />
	</a>
<?php endforeach; ?>

<?php echo $this->paginationControl(
					$this->paginator,
					'Sliding',
					'/partials/pagination.phtml'); ?>
	
