<?php echo $this->headScript()->appendFile('/js/3rdParty/jQuery.js'); ?>
<?php echo $this->headScript()->appendFile('/js/play.js'); ?>

<?php echo $this->question['question']; ?>

<div id="answer">
<span id="<?php echo $this->answers[0]; ?>" class="answer" ><?php echo $this->answers[1]; ?></span>
<span id="<?php echo $this->answers[2]; ?>" class="answer" ><?php echo $this->answers[3]; ?></span>
<span id="<?php echo $this->answers[4]; ?>" class="answer" ><?php echo $this->answers[5]; ?></span>
<span id="<?php echo $this->answers[6]; ?>" class="answer" ><?php echo $this->answers[7]; ?></span>
</div>

<?php var_dump($this->categories); ?>
