<?php echo $this->headScript()->appendFile('/js/3rdParty/jQuery.js'); ?>
<?php echo $this->headScript()->appendFile('/js/calculate/index.js'); ?>
<?php foreach ($this->numberPairs as $pair): ?>
	<div>
	<span class="numberOne" id="<?php echo $pair->numberOne; ?>"><?php echo $pair->numberOne; ?></span>
	<span class="operator" id="<?php echo $pair->operator; ?>"><?php echo $pair->displayOperator; ?></span>
	<span class="numberTwo" id="<?php echo $pair->numberTwo; ?>"><?php echo $pair->numberTwo; ?></span>
	<input class="textfield" type="textfield" />
	</div>
<?php endforeach; ?>
