<?php echo $this->headScript()->appendFile('/js/3rdParty/jQuery.js'); ?>
<?php echo $this->headScript()->appendFile('/js/calculate/index.js'); ?>

<form id="calculate-form" action="/calculate/result" method="POST">

<?php $length = count($this->numberPairs); ?>
<?php foreach ($this->numberPairs as $key => $pair): ?>
	<div>
	<span class="numberOne" id="<?php echo $pair->getNumberOne(); ?>"><?php echo $pair->getNumberOne(); ?></span>
	<span class="operator" id="<?php echo $pair->getOperator(); ?>"><?php echo $pair->getDisplayOperator(); ?></span>
	<span class="numberTwo" id="<?php echo $pair->getNumberTwo(); ?>"><?php echo $pair->getNumberTwo(); ?></span>

	<?php  $id = ($length -1 === $key) ? "last" : ''; ?>
	<input id="<?php echo $id; ?>" class="textfield" name="<?php echo $key; ?>" type="textfield" />

	<span class="right">Richtig</span>
	<span class="wrong">Falsch</span>
	</div>
<?php endforeach; ?>

</form>
