<a href="/calculate/calc/l/<?php echo $this->level; ?>/op/plus">Plus</a>
<br />
<a href="/calculate/calc/l/<?php echo $this->level; ?>/op/minus">Minus</a>
<br />
<a href="/calculate/calc/l/<?php echo $this->level; ?>/op/multi">Mal</a>
<br />
<a href="/calculate/calc/l/<?php echo $this->level; ?>/op/divide">Geteilt</a>
<br />
<a href="/calculate/calc/l/<?php echo $this->level; ?>/op/all">All</a>
<br />
