<?php foreach ($this->list as $operation): ?>
	<a href="/calculate/calc/l/<?php echo $this->level; ?>/op/<?php echo $operation['op']; ?>"><?php echo $operation['tx']; ?></a> | 
	
	<?php if (isset($operation['lr']) && $operation['lr'] !== false): ?>
		<?php echo $operation['lr']['right']; ?> Richtig in
		<?php echo $operation['lr']['time']; ?> Sekunden
		<?php echo ($operation['lr']['next'] === 'N') ? 'Nicht erreicht' : 'Super'; ?> 
	<?php endif; ?>
	<br />
<?php endforeach; ?>
