<?php $this->headLink()->appendStylesheet('/css/index/index.css'); ?>
<?php echo $this->headScript()->appendFile('/js/3rdParty/jQuery.js'); ?>
<?php echo $this->headScript()->appendFile('/js/3rdParty/jquery.tooltip.js'); ?>
<?php echo $this->headScript()->appendFile('/js/index/index.js'); ?>

<div id="start-info">
<p>Bildung ist die gesteigerte Fähigkeit, jedem Gegenstand ein Interesse abzugewinnen.</p>
<span>Gerhard von Mutius</span>
</div>

<div class="random">Zufallsgame
	<span class="postfix">
	<input title="Zufallsfragen im Multiple Choice Modus spielen" type="button" value="MC" class="qtypeButton"  onClick="javascript:window.location.replace('<?php echo $this->randomMCLink; ?>');"/>
	<input title="Zufallsfragen im Direkteingabe Modus spielen" type="button" value="TXT" class="qtypeButton"  onClick="javascript:window.location.replace('<?php echo $this->randomTXTLink; ?>');"/>
	</span>
</div>

<h2 id="whats-next-head" title="Wenn du angemeldet bist, werden dir hier Games angezeigt, die du noch nie gespielt hast, und welche, die du wiederholen solltest.">Vorschläge</h2>
<div id="next">
	<img src="/img/loader.gif" />

</div>
