<?php $this->headLink()->appendStylesheet('/css/index/index.css'); ?>
<?php echo $this->headScript()->appendFile('/js/3rdParty/jQuery.js'); ?>
<?php echo $this->headScript()->appendFile('/js/3rdParty/jquery.tooltip.js'); ?>
<?php echo $this->headScript()->appendFile('/js/index/index.js'); ?>

<div id="start-info">
<p>Bildung ist die gesteigerte Fähigkeit, jedem Gegenstand ein Interesse abzugewinnen.</p>
<span>Gerhard von Mutius</span>
</div>

<hr />
<iframe src="/game/index/noframe/1" width="100%" height="600px" name="game" frameborder="0">



</iframe>



<hr />
