<?php echo $this->headLink()->appendStylesheet('/css/index/index.css'); ?>

sprichwort zum wissen

login oder registrieren

aktuelle spiele
<br />
<br />
<br />
<br />

<h2>Vorschläge</h2>

<?php foreach ($this->next as $result): ?>
	
	<a href="<?php echo $result['link']; ?>">
	<div title="<?php echo $result['tooltip']; ?>" class="whats-next">
		<div class="header"><span class="title"><?php echo $result['name']; ?></span>
			<span class="postfix"><?php echo $result['postfix']; ?></span></div>
	</div>
	</a>
<?php endforeach; ?>
