<?php if (!empty($this->next)): ?>
<?php foreach ($this->next as $result): ?>
	
		<?php if ($result['type'] !== null): ?>
			<a href="<?php echo $result['link']; ?>">
			<div title="<?php echo $result['tooltip']; ?>" class="whats-next">
				<div class="header"><span class="title"><?php echo $result['name']; ?></span>
					<span class="postfix"><?php echo $result['postfix']; ?></span>
			</div>
			</div>
			</a>
		<?php else: ?>

		<div title="<?php echo $result['tooltip']; ?>" class="whats-next">
				<div class="header"><span class="title"><?php echo $result['name']; ?></span>
					<span class="postfix">
						<input title="<?php echo ($result['tooltip'] !== '') ? $result['tooltip'] . '<br />' : ''; ?>Spiele im Multiple Choice Modus" type="button" value="MC" class="qtypeButton"  onClick="javascript:window.location.replace('<?php echo $result['linkMC']; ?>');"/>
						<input title="<?php echo !isset($result['tooltip']) ? $result['tooltip'] . '<br />' : ''; ?>Spiele im Direkteingabe Modus" type="button" value="TXT" class="qtypeButton"  onClick="javascript:window.location.replace('<?php echo $result['linkTXT']; ?>');"/>
						<?php echo $result['postfix']; ?></span>
			</div>
			</div>

		<?php endif; ?>

<?php endforeach; ?>

<?php else: ?>
	<?php echo $this->message; ?>
<?php endif; ?>
