
<?php if($this->isAnswerRight): ?>
	<div class="success"><?php echo $this->rightAnswer; ?> ist richtig. Sehr gut!</div>
<?php else: ?>
	<div class="error"><?php echo $this->myAnswer; ?> ist falsch.
	<?php echo $this->rightAnswer; ?> wäre richtig gewesen.</div>
<?php endif; ?>

<div id="result">
Fragen: <?php echo $this->playedQuestions; ?>
 Richtig: <?php echo $this->rightAnswers; ?>
 Falsch: <?php echo $this->wrongAnswers; ?>
</div>

<a href="<?php echo $this->baseUrl . '/game'; ?>">Weiter</a>
