
<a id="next" href="<?php echo $this->baseUrl . '/game'; ?>">Weiter</a>

<?php if($this->isAnswerRight): ?>
	<div class="success"><b><?php echo $this->rightAnswer; ?><b/> ist richtig. Sehr gut!</div>
<?php else: ?>
	<div class="error"><?php echo $this->myAnswer; ?> ist falsch.
	<b><?php echo $this->rightAnswer; ?></b> wäre richtig gewesen.</div>
<?php endif; ?>

<div id="result">
Fragen: <?php echo $this->playedQuestions; ?>
 Richtig: <?php echo $this->rightAnswers; ?>
 Falsch: <?php echo $this->wrongAnswers; ?>
</div>

