<?php  $this->headScript()->appendFile('/js/3rdParty/jQuery.js'); ?>
<?php  $this->headScript()->appendFile('/js/3rdParty/jquery.countdown.js'); ?>
<?php  $this->headScript()->appendFile('/js/3rdParty/jquery.countdown-de.js'); ?>
<?php  $this->headScript()->appendFile('/js/3rdParty/jquery.domwindow.js'); ?>
<?php  $this->headScript()->appendFile('/js/3rdParty/jquery.tooltip.js'); ?>
<?php  $this->headScript()->appendFile('/js/3rdParty/jquery.tablednd.js'); ?>
<?php  $this->headScript()->appendFile('/js/3rdParty/jquery.fancybox.js'); ?>
<?php  $this->headScript()->appendFile('/js/3rdParty/OpenLayers.js'); ?>
<?php  $this->headScript()->appendFile('/js/game/play.js'); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->headLink()->appendStylesheet('/css/3rdParty/jquery.countdown.css'); ?>
<?php echo $this->headLink()->appendStylesheet('/css/3rdParty/jquery.fancybox.css'); ?>
<?php echo $this->headLink()->appendStylesheet('/css/game/game.css'); ?>

<?php if ($this->questionNotFound !== true): ?>	

	<div id="game">
			<h1><?php echo $this->question['question']; ?></h1>

			


		<div id="answer_score">
		
		<?php if ($this->objectType === 'default'): ?>
			<?php echo $this->render('/game/index/default.phtml'); ?>
		<?php elseif ($this->objectType === 'sorter'): ?>
			<?php echo $this->render('/game/index/sorter.phtml'); ?>
		<?php elseif ($this->objectType === 'map'): ?>
			<?php echo $this->render('/game/index/map.phtml'); ?>
		<?php endif; ?>

			<br/>
			<br/>
		<?php echo $this->render('/game/shared/result.phtml'); ?>
			</div>
			</div>
			<?php if($this->role === 'manager'): ?>
				<a href="/createquestion/editquestion/question/<?php echo $this->question['questionid']; ?>" target="_blank">Frage bearbeiten</a>
			<?php endif; ?>
	</div>




<?php else: ?>

	<p>Die Frage existiert nicht.</p>
	<p>Error: <?php echo $this->errorId; ?>|<?php echo $this->className; ?></p>
	<a href="<?php echo $this->baseUrl . '/game'; ?>">Nächste Frage</a>

<?php endif; ?>



