<?php echo $this->headScript()->appendFile('/js/3rdParty/jQuery.js'); ?>
<?php echo $this->headScript()->appendFile('/js/3rdParty/jquery.countdown.js'); ?>
<?php echo $this->headScript()->appendFile('/js/3rdParty/jquery.countdown-de.js'); ?>
<?php echo $this->headScript()->appendFile('/js/3rdParty/jquery.domwindow.js'); ?>
<?php echo $this->headScript()->appendFile('/js/game/play.js'); ?>
<?php echo $this->headLink()->appendStylesheet('/css/3rdParty/jquery.countdown.css'); ?>
<?php echo $this->headLink()->appendStylesheet('/css/game/game.css'); ?>

<?php if ($this->questionNotFound !== true): ?>	

	<div id="game">
			<h1><?php echo $this->question['question']; ?></h1>
			<?php //echo $this->question['level']; ?>

			<?php foreach($this->categories as $category): ?>
			<?php //echo $category; ?>
			<?php endforeach; ?>


			<div id="answer_score">
			<img height="300px" id="gameimg" src="<?php echo $this->baseUrl . '/img/question/' . $this->question['image']; ?>" alt="fragebild" />
			<div>
			<div style="width: 60px;" id="countdown"></div>

			<?php if ($this->answers !== 'nochoice'): ?>
				<input type="button" id="<?php echo $this->answers[0]; ?>" class="answer" value="<?php echo $this->answers[1]; ?>" />
				<input type="button" id="<?php echo $this->answers[2]; ?>" class="answer" value="<?php echo $this->answers[3]; ?>" />
				<input type="button" id="<?php echo $this->answers[4]; ?>" class="answer" value="<?php echo $this->answers[5]; ?>" />
				<input type="button" id="<?php echo $this->answers[6]; ?>" class="answer" value="<?php echo $this->answers[7]; ?>" />
			<?php else: ?>
				<span id="textfield"><input type="text" id="input_answer" /></span>
				<?php if ($this->question['hint']): ?>
					<span id="hint">Eingabehilfe: <?php echo $this->question['hint']; ?></span>
				<?php endif; ?>
				<input type="button" id="send_answer" value="Beantworten" />
			<?php endif; ?>
			<br/>
			<br/>
			<div id="result">
			Insgesamt: <?php echo $this->numberOfQuestions; ?> | 
			Noch übrig: <?php echo $this->currentNumberOfQuestions; ?> | 
			Beantwortet: <?php echo $this->playedQuestions; ?> | 
			Richtig: <?php echo $this->rightAnswers; ?> | 
			Falsch: <?php echo $this->wrongAnswers; ?> 
			</div>
			</div>
			</div>
			<?php if($this->role === 'manager'): ?>
				<a href="/createquestion/editquestion/question/<?php echo $this->question['questionid']; ?>" target="_blank">Frage bearbeiten</a>
			<?php endif; ?>
	</div>
<?php else: ?>

	<p>Die Frage existiert nicht.</p>
	<p>Error: <?php echo $this->errorId; ?>|<?php echo $this->className; ?></p>
	<a href="<?php echo $this->baseUrl . '/game'; ?>">Nächste Frage</a>

<?php endif; ?>



