<?php if (!$this->questionType === 'srt'): ?>

<div><img title="<?php echo $this->answerText; ?>" height="300px" id="gameimg" src="<?php echo $this->baseUrl . '/img/question/' . $this->image; ?>" alt="antwortbild" /></div>

<input type="button" id="next" value="Weiter" onClick="javascript:window.location.replace('/game');" />

<div class="error">Ihre Zeit ist leider um.
<b><?php echo $this->rightAnswer; ?></b> wäre richtig gewesen.
</div>

<?php else: ?>

		Falsch
		<?php foreach ($this->rightAnswer as $rightAnswer): ?>
			<?php echo $rightAnswer; ?>
		<?php endforeach; ?>	
<?php endif; ?>

<div id="result">

	Insgesamt: <?php echo $this->numberOfQuestions; ?> | 
	Noch übrig: <?php echo $this->currentNumberOfQuestions; ?> | 
	Beantwortet: <?php echo $this->playedQuestions; ?> | 
 	Richtig: <?php echo $this->rightAnswers; ?>
 	Falsch: <?php echo $this->wrongAnswers; ?>
</div>
