<h1>FAQ - Informationen zu allgemein-bildung.de</h1>

<b><p>allgemein-bildung.de ist eine Wissenwebsite. Sie stellt verschiedene Quizes aus unterschiedlichen Kategorien zur Verfügung. Dabei wird die Allgemein Bildung trainiert.</p></b>

<h2>Zum Fragemodus</h2>

<ul>
	<li>Multiple Choice - MC</li>
	<p>Im Multiple Choice Modus (MC) bekommt der Nutzer vier Antwortmöglichkeiten vorgegeben.</p>
	<li>Direkteingabe - TXT</li>
	<p>Im Direkteingabe Modus (TXT) bekommt der Nutzer keine Antwortmöglichkeiten. Dieser Modus ist somit schwieriger als der Muliple Choice Modus</p>
	<li>Lerngame</li>
	<p>Beim Lerngame werden die Fragen eines Games zweimal durchgespielt. Dadurch wird dieses Game besonders trainiert. Alle falschen Antworten werden ebenfalls nocheinmal gespielt. <br /> 
	Das Lerngame kann man sowohl im Multiple Choice (MC) oder Direkteingabe (TXT) Modus spielen.</p>
</ul>
