<?php if ($this->game->hasModeChanged()): ?>
	<div  id="learndialog"></div>
	<span id="learndialogid"><?php echo $this->game->getMode(); ?></span>
	<script type="text/javascript">
		var mode = $("#learndialogid").html();
		var message = "";
		if (mode == 0) {
			message = "Du spielst dieses Game im Lernmodus. Dabei spielst du alle Fragen zweimal durch, um sie besonders gut im Gedächtnis zu behalten!";
		} else if (mode == 1) {
			message = "Die zweite Runde beginnnt. Jetzt kommen die gerade gespielten Fragen nocheinmal!";
		} else {
			message = "Endspurt!. Abschließend kommen noch die Fragen, die du bisher falsch beantwortet hattest.";
		}
		var title = "Lernmodus";
		$("#learndialog" ).dialog({ title: title,
									height: 280,
							   buttons: [{ text: "Ok",
								click: function() { 
									$(this).dialog("close"); }
								}]
		 });
		$("#learndialog").html(message);

	</script>
<?php endif; ?>


<div id="result">
	<?php 	$scores 	= $this->game->getScore()->getChilds(); 
			$mode 	= $this->game->getMode(); 
		foreach ($scores as $key => $score): ?>
			
			<div <?php if ($mode === $key) echo "style='background-color: white'"; ?>>
			Insgesamt: 		<?php echo $this->game->getNumberOfQuestionsForKey($key); ?> | 
			Noch übrig: 	<?php echo $this->game->getCurrentNumberOfQuestionsForKey($key); ?> | 
			Beantwortet: 	<?php echo $score->getPlayedQuestions(); ?> | 
			Richtig: 		<?php echo $score->getRightAnswers(); ?> |
			Falsch: 		<?php echo $score->getWrongAnswers(); ?>
			</div>

	<?php endforeach; ?>
	</div>

