<?php if ($this->game->gameStarts()): ?>
	<div  id="mclearndialog"></div>
	<script type="text/javascript">
		var message = "Spiele die Fragen im Direkteingabe Modus. Wenn du sie falsch beantwortest, bekommst du die Chance, im Multiple Choice Modus die richtige Antwort zu finden.";
		var title = "Lernmodus";
		$("#mclearndialog" ).dialog({ title: title,
									height: 280,
							   buttons: [{ text: "Ok",
								click: function() { 
									$(this).dialog("close"); }
								}]
		 });
		$("#mclearndialog").html(message);

	</script>
<?php endif; ?>


<div id="result">

	Insgesamt: <?php echo $this->game->getNumberOfQuestions(); ?> | 
	Noch übrig: <?php echo $this->game->getCurrentNumberOfQuestions(); ?> | 
	Beantwortet: <?php echo $this->game->getScore()->getPlayedQuestions(); ?> | 
 	Sofort Richtig: <?php echo $this->game->getScore()->getRightTXTAnswers(); ?> |
 	Richtig im 2. Versuch: <?php echo $this->game->getScore()->getRightMCAnswers(); ?> |
 	Falsch: <?php echo $this->game->getScore()->getWrongAnswers(); ?>
</div>

