<?php echo $this->headScript()->appendFile('/js/3rdParty/jQuery.js'); ?>
<?php echo $this->headScript()->appendFile('/js/gamelist/category.js'); ?>
<?php echo $this->headLink()->appendStylesheet('/css/gamelist/category.css'); ?>

<h1>Kategorien</h1>

<p class="error" style="width:665px; display:none;">Bitte wähle mindestens eine Kategorie aus</p>

<form action="/gamelist/categoryresult" method="POST" id="form">

<?php foreach($this->categories as $categoryId => $category): ?>
	<div class="category">
		<input type="checkbox" name="cat[]" value="<?php echo $categoryId; ?>">
		<?php echo $category; ?>
	</div>
<?php endforeach; ?>

<div id="send"><input type='button' value='Suchen' /></div>

</form>
