<?php echo $this->headScript()->appendFile('/js/3rdParty/jQuery.js'); ?>
<?php echo $this->headScript()->appendFile('/js/gamelist/index.js'); ?>
<?php echo $this->headLink()->appendStylesheet('/css/gamelist/index.css'); ?>


<h1>Games</h1>

<a href="/gamelist/category">Nach Kategorien auswählen</a>
<?php if ($this->userId !== null): ?>
	<a href="/result/games">Zuletzt gespielte Fragen</a>
<?php endif; ?>

<?php echo $this->render('gamelist.phtml');
