<h1>Games</h1>

<?php foreach($this->gameList as $game): ?>
	<a href="/gamelist/game/g/<?php echo $game['gameid']; ?>">
		<?php echo $game['name']; ?>
	</a>
	<?php echo '(' . $game['numberOfQuestions'] . ')'; ?>
	<a href="/game/index/play/<?php echo md5('nextgame!'); ?>/g/<?php echo $game['gameid']; ?>/qtyp/mc/sh/1">
		Multiple Choice
	</a><br />
	<a href="/game/index/play/<?php echo md5('nextgame!'); ?>/g/<?php echo $game['gameid']; ?>/qtyp/txt/sh/1">
		Direkteingabe
	</a><br />
<?php endforeach; ?>
