<h1>Lernkurve</h1>

<a href="/next/noplay">Ungespielt</a><br />
<a href="/result/next">Gemischt</a><br />
<br />

<a href="/next/show/t/PN/qt/mc">Jetzt im Multiple Choice Modus spielen</a><br />
<a href="/next/show/t/LG/qt/mc">Learn Game</a><br />
<a href="/next/show/t/PW/qt/mc">Falsche im Learn Game</a><br />
<a href="/next/show/t/PN/qt/txt">Jetzt im Direkteingabemodus Modus spielen</a><br />
<a href="/next/show/t/LG/qt/txt">Learn Game TXT</a><br />
<a href="/next/show/t/PW/qt/txt">Falsche TXt im Learn Game</a><br />
<a href="/next/show/t/PL/qt/txt">Perfekt</a><br />
