
<?php echo $this->headLink()->appendStylesheet('/css/next/index.css'); ?>

<h1 style="text-align: center;">Lernpyramide</h1>
<br />
<br />


<div style="width:520px" class="link"><a href="/next/show/t/PL/qt/txt">Diese Games beherrscht du super!</a></div>
<div style="width:560px" class="link"><a href="/next/show/t/PW/qt/txt">Falsche Fragen im Learn Modus</a></div>
<div style="width:600px" class="link"><a href="/next/show/t/LG/qt/txt">Direkteingabe im Learn Modus</a></div>
<div style="width:640px" class="link"><a href="/next/show/t/PN/qt/txt">Jetzt im Direkteingabemodus Modus spielen</a></div>
<div style="width:680px" class="link"><a href="/next/show/t/PW/qt/mc">Falsche Fragen im Learn Modus</a></div>
<div style="width:720px" class="link"><a href="/next/show/t/LG/qt/mc">Multiple Choice im Learn Modus</a></div>
<div style="width:760px" class="link"><a href="/next/show/t/PN/qt/mc">Jetzt im Multiple Choice Modus spielen</a></div>
<div style="width:800px" class="link"><a href="/next/noplay">Ungespielte Games</a></div>

<br />
<br />
