<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
	<?php $this->headLink()->appendStylesheet('/css/main.css'); ?>
	<?php echo $this->headLink(); ?>
  </head>
  <body> 
		<div id="header">
			<h1><a href="/"><img src="/img/header.png" alt="allgemein-bildung.de" height="80px" /></a></h1>

				<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
					<?php $user = new Zend_Session_Namespace('user'); ?>
					<div class="login">Herzlich Willkommen 
						<b><?php echo $user->user['username']; ?></b>
						<a href="/index/logout">&raquo;Logout</a>
					</div>
				<?php else: ?>
					<div class="login">Sie sind nicht angemeldet
					<a href="/index/login">&raquo;Login</a></div>
				<?php endif; ?>

				<ul>
					<li><a href="/index">HOME</a></li>
					<li><a href="/gamelist">Gameliste</a></li>
					<li><a href="/gamelist/category">Kategorien</a></li>
					<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
					<li><a href="/next">Lernpyramide</a></li>
					<li><a href="/result/next">Vorschläge</a></li>
					<li><a href="/result/games">Zuletzt gespielt</a></li>
					<?php endif; ?>
				</ul>
		</div>

		<div id="content">
				<?php echo $this->layout()->content; ?>
		</div>

		<div id="footer">
			<div id="footer-links">
			<a href="/content/faq">Faq</a> | 
			<a href="/content/imprint">Impressum</a>
			</div>
		</div>


<h1>AB Localhost</h1>
    <p><fb:login-button autologoutlink="true"></fb:login-button></p>
    <p><fb:like></fb:like></p>

    <div id="fb-root"></div>
    <script>
      window.fbAsyncInit = function() {
        FB.init({appId: '144739782237622', status: true, cookie: true,
                 xfbml: true});
      };
      (function() {
        var e = document.createElement('script');
        e.type = 'text/javascript';
        e.src = document.location.protocol +
          '//connect.facebook.net/de_DE/all.js';
        e.async = true;
        document.getElementById('fb-root').appendChild(e);
      }());
    </script>
  </body>


  </body>
</html>

