<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headLink()->appendStylesheet('/css/main.css'); ?>
  </head>
  <body> 
		<div id="header">
			<h1><a href="/"><img src="/img/header.png" alt="allgemein-bildung.de" height="80px" /></a></h1>
				<ul>
					<li><a href="/index/login">Login</a></li>
					<li><a href="/gamelist">Gameliste</a></li>
					<li><a href="/result/games">REsults</a></li>
					<li><a href="/createquestion/questionlist">Angelegte Fragen</a></li>
					<li><a href="/question">Fragen</a></li>
				</ul>
		</div>

		<div id="content">
				<?php echo $this->layout()->content; ?>
		</div>

		<div id="footer">
			impressum etc.
		</div>
  </body>
</html>

