	<!-- right answer -->
	<?php if ($this->isAnswerRight): ?>
		<div class="success"><b>Deine Antwort ist richtig. Sehr gut!</b></div>
		<table class="sorter-numbers">
			<?php foreach ($this->rightAnswer['keys'] as $key): ?>
				<tr><td><?php echo $key; ?></td></tr>
			<?php endforeach; ?>
		</table>
		<table class="sorter-answers" style="background-color: #1EE664;">
			<?php foreach ($this->rightAnswer['answers'] as $key => $rightAnswer): ?>
				<tr><td><?php echo $rightAnswer; ?></td>
				<?php if(isset($this->rightAnswer['data'])): ?>
					<td><?php echo $this->rightAnswer['data'][$key]; ?></td>
				<?php endif; ?>	
				</tr>
			<?php endforeach; ?>
		</table>

	<!-- wrong answer -->
	<?php else: ?>	
		<div class="error">Deine Antwort ist leider falsch.</div>
		<table class="sorter-numbers">
			<?php foreach ($this->rightAnswer['keys'] as $key): ?>
				<tr><td><?php echo $key; ?></td></tr>
			<?php endforeach; ?>
		</table>
		<table class="sorter-answers" style="float: left; background-color: #FFEBE8;">

			<?php for ($i = 0; $i < count($this->myAnswer['answers']); $i++): ?>
				<?php $class = (in_array($i, $this->myAnswer['wrong'])) ? 'sorter-red' : 'green'; ?>
				<tr class="<?php echo $class; ?>"><td><?php  echo ($this->myAnswer['answers'][$i] === "") ? 'Nicht gefüllt' : $this->myAnswer['answers'][$i]; ?></td></tr>
			<?php endfor; ?>	
		</table>
		<table class="sorter-answers" style="background-color: #1EE664">
			<?php foreach ($this->rightAnswer['answers'] as $key => $rightAnswer): ?>
				<tr><td><?php echo $rightAnswer; ?></td>
				<?php if(isset($this->rightAnswer['data'])): ?>
					<td><?php echo $this->rightAnswer['data'][$key]; ?></td>
				<?php endif; ?>	
				</tr>
			<?php endforeach; ?>	
		</table>

	<?php endif; ?>

<input type="button" id="sorter-next" value="Weiter" onClick="javascript:window.location.replace('/game');" />
