
<h1>Game anlegen</h1>

<?php if (!empty($this->questions)): ?>

<a href="<?php echo Model_LinkBuilder::getInstance()->getSessionTestGameLink(); ?>">Game testen</a>
 | <a href='/creategame/savegame'>Game abspeichern</a>
<br />
<br />

<?php foreach ($this->questions as $question): ?>
	<img height="100px" src="img/question/<?php echo $question['image']; ?>" />
	<?php echo $question['question']; ?>
	<hr />
<?php endforeach; ?>

<a href="<?php echo Model_LinkBuilder::getInstance()->getSessionTestGameLink(); ?>">Game testen</a>
 | <a href='/creategame/savegame'>Game abspeichern</a>

<?php else: ?>
<p>Zurzeit gibt es keine Fragen zum anlegen</p>
<?php endif; ?>
