
<h1>Game anlegen</h1>

<?php if (!empty($this->questions)): ?>

<?php echo "<a href='/game/index/play/".md5('nextgame!')."/test/".md5('testgame!'). "/se/" . md5('session!') . "'>Game testen</a>"; ?>
 | <a href='/creategame/savegame'>Game abspeichern</a>
<br />
<br />

<?php foreach ($this->questions as $question): ?>
	<img height="100px" src="img/question/<?php echo $question['image']; ?>" />
	<?php echo $question['question']; ?>
	<hr />
<?php endforeach; ?>

<?php echo "<a href='/game/index/play/".md5('nextgame!')."/test/".md5('testgame!'). "/se/" . md5('session!') . "'>Game testen</a>"; ?>
 | <a href='/creategame/savegame'>Game abspeichern</a>

<?php else: ?>
<p>Zurzeit gibt es keine Fragen zum anlegen</p>
<?php endif; ?>
