<?php echo $this->headScript()->appendFile('/js/3rdParty/jQuery.js'); ?>
<?php echo $this->headScript()->appendFile('/js/3rdParty/jquery.domwindow.js'); ?>
<?php echo $this->headScript()->appendFile('/js/createquestion/index.js'); ?>
<?php echo $this->headLink()->appendStylesheet('/css/createquestion/createquestion.css'); ?>

<h1>Neue Frage anlegen</h1>
<?php echo $this->form; ?>


<div id="imagePicker" style="display: none;"> 
<h1>Bilder Auswahl</h1> 
Namen zur Frage eingeben:
<input type="text" id="imageName" />
<div id="images"></div>
</div>
