<?php  $this->headScript()->appendFile('/js/3rdParty/OpenLayers.js'); ?>
<?php  $this->headScript()->appendFile('/js/game/map.js'); ?>
<?php echo $this->headScript(); ?>
<span style="display: none" id="timer-duration">60</span>	

<div id="map" style="width: 300px; height: 300px"></div>	
<span style="display:none" id="lat"><?php echo $this->answers['lat']; ?></span>
<span style="display:none" id="lon"><?php echo $this->answers['lon']; ?></span>
<div style="width: 60px; clear:left" id="countdown"></div>
