<?php  $this->headScript()->appendFile('/js/3rdParty/OpenLayers.js'); ?>
<?php  $this->headScript()->appendFile('/js/3rdParty/jquery-ui.js'); ?>
<?php  $this->headScript()->appendFile('/js/game/map.js'); ?>
<?php echo $this->headLink()->appendStylesheet('/css/3rdParty/jquery-ui.css'); ?>
<?php echo $this->headScript(); ?>
<span style="display: none" id="timer-duration">60</span>	

<div id="map-cont"><div id="map" style="width: 480px; height: 400px"></div>	</div>
<span style="display:none" id="lat"><?php echo $this->answers['lat']; ?></span>
<span style="display:none" id="lon"><?php echo $this->answers['lon']; ?></span>

<div id="dialog"></div>
